### ISSUE TITLE
Greek letters in lavaan plots

### ISSUE THREAD

**Issue by jknowles** [SachaEpskamp/semPlot#1]
Hi!

This package is absolutely fantastic. I was wondering if there is support for embedding Greek symbols either in edge labels, or in node labels, for plots coming from lavaan model fit objects. I have created a Gist showing a lavaan model and the beautiful plot this package produces, but how can Greek symbols be added to the plot?

I know you can use the delta\* notation in qgraph, but this makes lavaan fail on the front end. How could this work on the backend? Is this possible, or would that need to be a feature added to the tool?

Here is the Gist:

https://gist.github.com/4674473

**Comment by SachaEpskamp** [comment]
Thank you for your comments!

Greek letters are certainly intended to be usable, but it seems there are some problems with it now.

There are now two ways to use greek letters in qgraph, using an asterisk to plot the label in symbol font or to use expressions. I just noticed though that the latter only works if you have an expression without empty elements. In semPlot the 'as.expression' argument can be used to plot either edge or node labels as expressions. 

However, I just realized I completely forgot about adding an argument to overwrite the labels so that this can be used without having to use expressions or asterisks in the SEM syntax itself. Right now the easiest way to do this is store the result of semPaths (which is a qgraph object) and plot the graph again with different arguments:

``` r
Graph <- semPaths(fit,whatLabels="est",style="lisrel",
         residuals=TRUE)
Graph$labels[!grepl("x|y",Graph$labels)] <- paste0("*h",1:3)
qgraph(Graph)
```

I'll improve this functionality soon. Thank's for notifying me!

**Comment by SachaEpskamp** [comment]
I have added the functionality to qgraph that lists can be used for labels, which makes working with expressions quite easier (as you can now have only a few labels as expressions). In semPlot I added the arguments nodeLabels and edgeLabels that overwrite the labels before calling qgraph. It's quite a crude solution and can be made more user friendly but works for now. For example:

``` r
semPaths(fit,whatLabels="est",style="lisrel",
         residuals=TRUE, nodeLabels = 
           c(as.list(c(paste0("x",1:3), paste0("y",1:8))),
             list(expression(xi[1]),expression(eta[1]),expression(eta[2]))))
```

![qgraph](https://f.cloud.github.com/assets/1207242/115107/44ff6652-6bc2-11e2-9ad1-195f7eff51a2.png)

To do this you need the developmental versions (these here on gitHub) of both qgraph and semPlot.

**Comment by jknowles** [comment]
That looks fantastic. It doesn't even seem that crude to me! I'll have to pull down the dev versions of both packages and check it out. Thanks so much!
